# Generated by Django 4.0.6 on 2022-07-28 15:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masdatosusuario',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='masdatosusuario',
            name='link',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
