# Generated by Django 4.0.6 on 2022-07-26 16:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=30)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('autor', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(null=True)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
